---
extends:
  - eslint:recommended
  - prettier
  - prettier/prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
plugins:
  - import
env:
  es6: true
  mocha: true
  node: true
rules:
  curly:
    - error
    - all
  no-extra-boolean-cast:
    - 0
  no-console:
    - error
    - allow: [warn, error]
  spaced-comment:
    - error
    - always
  no-throw-literal:
    - error
  eqeqeq: 2
  guard-for-in: 2
  require-atomic-updates: off
  no-useless-escape: off
  no-prototype-builtins: off
  no-useless-catch: off
  sort-imports:
    - error
    - ignoreDeclarationSort: true
globals:
  expect: false
  globalInject: false
  inject: false
  module: false
  resetInjector: false
  should: false
  sinon: false
overrides:
  - files:
      - "*.js"
    rules:
      "no-unused-vars":
        - error
        - argsIgnorePattern: "^_"
          ignoreRestSiblings: true
      no-restricted-modules:
        - error
        - patterns: ["@cmc-server/*"] # @cmc-server imports are only allowed in TypeScript code.
settings:
  import/internal-regex: ^@cmc-server/
  react:
    version: detect
